# Database configuration props
spring:
  datasource:
    #url: jdbc:mysql://localhost:3306/studentsdb?createDatabaseIfNotExist=true
    url: jdbc:mysql://localhost:3306/studentsdb
    username: root
    password: mysql
  #spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

  # hibernate props
  jpa:
    show-sql: true
    hibernate:
      #ddl-auto: create-drop
      ddl-auto: none
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL5InnoDBDialect

logging:
  level:
    root: info
  file:
    path: c:/logs

server:
  port: 8090